### ISSUE TITLE
UML Klassendiagramm 

### ISSUE THREAD

**Issue by BuenyG** [Rahsch/javadrenaline#10]

**Comment by BuenyG** [comment]
![grafik](https://user-images.githubusercontent.com/104505844/168923957-7069b6e4-3d57-4138-8d24-808caf2d90e6.png)

Da ich morgen eventuell nicht teilnehmen kann am Praktikum hier ne ungefähre Idee von mir.
- Nutzer als Oberklasse die dann Attribute an die verschiedenen 3 Akteure vererbt
- Reservierung als Verbindung zwischen Nutzer und Raum/Sitzplatz
  => In dieser Klasse könnte man dann sozusagen Datum und Zeit + Reserviertes Objekt speichern
  => und andere Funktionen darüber auf diese Räume ausführen
- Man müsste halt schauen ob & wie wir die Liste der Räume die bereits reserviert sind und nicht reserviert sind einbaut

Schreibt ergänzungen am besten hier rein und euren Fortschritt + was noch fehlt wenn es in der Stunde nicht fertig wird

**Comment by Rahsch** [comment]
Mein Aktueller Stand des Klassendiagramms, ich setze mich nochmal später heute um 19:15 dran.
Die Datei im Anhang kann, nach dem entpacken der ZIP, einfach bei draw.io geöffnet werden.
[Klassendiagramm.zip](https://github.com/Rahsch/javadrenaline/files/8815462/Klassendiagramm.zip)

**Comment by Rahsch** [comment]
![Klassendiagramm_Javadrenaline](https://user-images.githubusercontent.com/88612168/171509034-c9f4741b-af33-49ad-ab28-0e643748a203.png)
Das ist mein letzter Stand bin nicht rechtzeitig fertig geworden. Hatte Probleme mit den Beziehungen zwischen den Klassen.
Als Zip Datei nochmal hier:
[Klassendiagramm_Javadrenaline2.0.zip](https://github.com/Rahsch/javadrenaline/files/8819044/Klassendiagramm_Javadrenaline2.0.zip)

**Comment by BuenyG** [comment]
Es sieht auf jeden Fall sehr gut aus.

**Comment by BuenyG** [comment]
![grafik](https://user-images.githubusercontent.com/104505844/181753543-a21de7fe-ab1e-4282-8b9a-1be5a0b9bb80.png)

**Comment by BuenyG** [comment]
![grafik](https://user-images.githubusercontent.com/104505844/181916227-87578069-90bb-4bc4-b7b4-e35bcd2d7eaa.png)

**Comment by Rahsch** [comment]
![Klassendiagramm](https://user-images.githubusercontent.com/88612168/182190739-c74cb300-f048-463d-906a-c7d344b3d7e6.png)

Hab noch die Klasse Administrator hinzugefügt

**Comment by BuenyG** [comment]
Auch wenn es komplett unnötig ist wenigstens etwas

**Comment by Rahsch** [comment]
In moodle ist die Abgabe bis heute 23:59, also nicht ganz so unnötig.

**Comment by BuenyG** [comment]
Hättest du dich mal gemeldet bei deinem Team anstatt auf den letzten drücker 8 std vorher was zu machen wüsstest du das wir bereits abgegeben haben

**Comment by Rahsch** [comment]
Ich habe nicht nur 8 Stunden vorher dran gesessen sondern eher paar Tage, aber die Kommunikation war nicht top gebe ich zu.
Ihr habt euch ja auch nicht Slack gemeldet, dass ihr euch zusammen getroffen habt, aber ist okay bin ja jetzt nicht hier um zu beafen.

Ich hab gesehen, dass Ihr abgegeben habt und werde es rausnehmen und dann noch mit dem, was ich geschrieben habe hinzufügen.

**Comment by BuenyG** [comment]
Ich trag deine Arbeit nach kein Ding

**Comment by Rahsch** [comment]
Ich Sitze schon dran, kein Stress

**Comment by BuenyG** [comment]
![Neues UML](https://user-images.githubusercontent.com/104505844/182201594-5ea9266c-9602-499a-ba02-c221cb915146.png)
