### ISSUE TITLE
Primary Use Case - Buche Raum/Sitzplatz

### ISSUE THREAD

**Issue by Rahsch** [Rahsch/javadrenaline#3]

**Comment by BuenyG** [comment]
![UseCase Beschreibung](https://user-images.githubusercontent.com/104505844/167319977-9dc0ffdc-c7b8-43c9-8adb-341f0d3671cb.png)
[UseCase Beschreibung.xlsx](https://github.com/Rahsch/javadrenaline/files/8647953/UseCase.Beschreibung.xlsx)

**Comment by BuenyG** [comment]
Beschreibung veraltet

**Comment by BuenyG** [comment]
![grafik](https://user-images.githubusercontent.com/104505844/181757372-5044be87-6000-428a-9433-9d62b8ac5cdc.png)
