### ISSUE TITLE
Primary Use Case - Darstellen Raum/Sitzplatz

### ISSUE THREAD

**Issue by Rahsch** [Rahsch/javadrenaline#4]

**Comment by S-Sediqi** [comment]
![UC02 Darstellen](https://user-images.githubusercontent.com/95696092/167956917-b16cf86c-7b04-4a32-986d-0fb6489520b2.png)
![UC02 Depiction_Page1](https://user-images.githubusercontent.com/95696092/167742556-af45c79f-b7b3-4798-92a4-ec6fb74d2b22.png)
![UC02 Depiction_Page2](https://user-images.githubusercontent.com/95696092/167742574-32e1a979-b0e8-48cd-9943-d4e9c272b8f2.png)
![UC02 Depiction_Page3](https://user-images.githubusercontent.com/95696092/167742583-3a195968-9b81-4f5b-8720-3fbb221a1a95.png)
![UC02 Depiction_Page4](https://user-images.githubusercontent.com/95696092/167742588-45d95ee2-145c-43de-92fe-3d7dfe7ab622.png)
![UC02 Depiction_Page5](https://user-images.githubusercontent.com/95696092/167742594-d8a1f087-d24e-4d17-84d6-e58fedb73362.png)
![UC02 Depiction_Page6](https://user-images.githubusercontent.com/95696092/167742644-54a2d478-06be-4a86-8cef-6fb2301605cc.png)
[UC02 Depiction.pdf](https://github.com/Rahsch/javadrenaline/files/8665591/UC02.Depiction.pdf)
[UC02 Darstellen.pdf](https://github.com/Rahsch/javadrenaline/files/8673730/UC02.Darstellen.pdf)
