### ISSUE TITLE
Beschreibung der Prozesse

### ISSUE THREAD

**Issue by Rahsch** [Rahsch/javadrenaline#8]

**Comment by ceyh61** [comment]
[ProzessBeschreibung.docx](https://github.com/Rahsch/javadrenaline/files/8669213/ProzessBeschreibung.docx)

**Comment by ceyh61** [comment]
Kurze Beschreibung unserer Vorgehensweise, bei der aktuellen Abgabe, mit Verbesserungsmöglichkeiten
